### ISSUE TITLE
Avoid RDF alias name conflicts for alias `lib`

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-semweb#43]
Change RDF alias `lib` to something a user is less likely to redefine.  Defined in module `semweb/rdf_library`.

**Comment by JanWielemaker** [comment]
I don't think it should be called `swi_lib`.  It is not SWI library.  It is a self-made version of the `void` namespace before that existed.  Now it uses `void` where possible but still the old `lib` for things that are not in void.  May be `voidex` (as _void extensions_)?

**Comment by wouterbeek** [comment]
+1 for `voidex`.  I'll also register that over at https://prefix.cc
