### ISSUE TITLE
Numeric constraint does not follow test case

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-semweb#54]
The following fails:

```prolog
?- rdf_assert(s, p, 1.0).
?- { X == 1 }, rdf(_, _, X).
```

But it should succeed according to the following test case:

```prolog
test(eq, set(X == [ 1^^xsd:byte,
                    1^^xsd:integer,
                    1.0^^xsd:double
                  ])) :-
    { X == 1 },
    rdf(_,_,X).
```

**Comment by wouterbeek** [comment]
My locale was set to `nl_NL.UTF8`.  Changing the locale to `en_US.UTF8` (in my case through the GNOME language settings dialog) and restarting fixed the issue.

**Comment by wouterbeek** [comment]
Yep, this one is fixed by changing the locale (not properly set on Ubuntu by default for some reason...)

**Comment by JanWielemaker** [comment]
Of course, the locale shouldn't matter and AFAIK this was fixed after the initial report.   In any case, I cannot reproduce it any more.  Thanks for closing.
