### ISSUE TITLE
Stream pair warnings in Turtle parser

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-semweb#57]
Very recently I have started receiving warnings like the following in the Turtle parser:

```
Warning: Ambiguous operation on stream pair <stream>(0x555efa86f980,0x555efa8b2a40)
```

This occurs when the C-based predicate `create_turtle_parser/3` is called in the following context:

```prolog
rdf_process_turtle(In, OnObject, Options) :-
    base_uri(In, BaseURI, Options),
    option(graph(Graph), Options, BaseURI),
    setup_call_cleanup(
        ( open_input(In, Stream, Close),
          create_turtle_parser(Parser, Stream, Options)
        ),
        ( process_turtle(Parser, Stream, OnObject, Graph,
                         [ parse(statement)
                         ]),
          post_options(Parser, Options)
        ),
        ( destroy_turtle_parser(Parser),
          call(Close)
        )).
```

This probably has a simple fix, but I do not see a stream pair here at all?

**Comment by JanWielemaker** [comment]
HTTP streams are stream pairs.   The warning is benign if you want to access the input stream (as is the case here).   Pushed a fix (84200d2d2fc9ce75d5e7f9a45ac9afa852fda082).
