### ISSUE TITLE
Unexpected error when parsing Turtle

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-semweb#62]
When parsing the following line of Turtle:

```turtle
@prefix dbp: <http://dbpedia.org/property/> .
@prefix dbr: <http://dbpedia.org/resource/> .
dbr:Germany_at_the_2006–08_European_Nations_Cup	dbp:stadium	dbr:Amsterdam .
```

SWI emits the following error while parsing:

```prolog
?- [library(semweb/rdf_db)].
?- [library(semweb/turtle)].
?- rdf_load('test.ttl', [format(turtle)]).
ERROR: /home/wbeek/tmp/test.ttl:3:23: Syntax error: PN_PREFIX expected
```

The input data seems to be correct and all used prefixes are defined.

**Comment by JanWielemaker** [comment]
The `–` is not the ASCII `-`, but Unicode point `8211` which is apparently not allowed here.

**Comment by wouterbeek** [comment]
Thanks for the info, opened [an issue](https://github.com/drobilla/serd/issues/5) for this in Serd (which does parse this Turtle snippet with no warning).
