### ISSUE TITLE
N-Triples data with no whitespace between terms cannot be parsed

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-semweb#64]
While we are waiting on W3C to come up with the grammar for Turtle-family languages in #60, it is clear that it should be possible to parse N-Triples data that has no whitespace between terms.

E.g., the following should be parsed:

```n-triples
<x:x><y:y><z:z>.
```

**Comment by JanWielemaker** [comment]
A quick check tells me the Turtle parser already does accept this.  I don't know whether it will correctly parse all corner cases, but we'll have to wait for a complete specification and test cases for that.  The ntriples does require an explicit white space.  At some point I stopped following the W3C discussion.  Will this (for sure) also apply to ntriples?  I'm very reluctant to remove the whitespace test to reenforce it again in a couple of months.

**Comment by wouterbeek** [comment]
@JanWielemaker I've changed the issue title and body to reflect that this indeed applies to the N-Triples parser (and not to the Turtle parser).

The W3C discussion is about whether or not the use of whitespace needs to be encoded into the EBNF grammar.  It is considered 'clear' that zero whitespace between terms is allowed.

There is already a test case for this in the N-Triples 1.1 test suite.  It's called `minimal_whitespace.nt` and has the following content:

```n-triples
<http://example/s><http://example/p><http://example/o>.
<http://example/s><http://example/p>"Alice".
<http://example/s><http://example/p>_:o.
_:s<http://example/p><http://example/o>.
_:s<http://example/p>"Alice".
_:s<http://example/p>_:bnode1.
```

**Comment by wouterbeek** [comment]
MWE:

```prolog
:- use_module(library(apply)).
:- use_module(library(semweb/rdf_ntriples)).
:- use_module(library(yall)).

run :-
  setup_call_cleanup(
    open_string("<s><p><o>.", In),
    rdf_process_ntriples(In, [L,_]>>maplist(writeln, L), []),
    close(In)
  ).
```

**Comment by JanWielemaker** [comment]
Patch is simpel.   After that we get some failing tests.   Also my reading is that a space is not required.   Looks like it used to be required though?   Are we sure it is not required?  Then I'll push the patch.

**Comment by wouterbeek** [comment]
https://www.w3.org/TR/n-triples/
> White space (tab U+0009 or space U+0020) is used to separate two terminals which would otherwise be (mis-)recognized as one terminal.

**Comment by JanWielemaker** [comment]
Possibly.   Might also come from an older document.  Surely it was pretty much on purpose with an explicit condition and test :smile:  Committed the patch.
