### ISSUE TITLE
Cannot parse graph keyword in TRiG

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-semweb#85]
The following cannot be parsed by `turtle.pl`:

```trig
graph <g:g> {
  <s:s> <p:p> <o:o>.
}
```

The graph keyword is allowed in the TRiG grammar but is not yet implemented by the parser.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 54273b6644d1c8c964271b9cb56d7964183794dc.   Not perfect as it basically simply ignores a GRAPH keyword in a place where it may appear, which implies you do not have to start a graph afterwards.  Fixing that requires some nasty state management in the current design.

**Comment by wouterbeek** [comment]
@JanWielemaker This fix does not work when the graph term is a prefixed IRI with alias `graph`:

```ttl
prefix graph: <x:x>
graph graph:x {
  <x:x> <x:x> <x:x>.
}
```

**Comment by JanWielemaker** [comment]
I see.  Guess I need a proper test that the graph keyword is indeed followed by a graph.

**Comment by wouterbeek** [comment]
Thanks Jan, this seems to work fine now.
