### ISSUE TITLE
Installation Guidance

### ISSUE THREAD

**Issue by DangMinh24** [SWI-Prolog/packages-semweb#97]
Hi, I know this question may sound silly, but can anyone help me with installing `semweb`? It seems like I can not install it as a regular `prolog` package (the structure of this project is not similar to ['prolog' package](https://www.swi-prolog.org/howto/Pack.html)).

**Comment by JanWielemaker** [comment]
It is an internal package that is installed when building the system unless explicitly disabled.   So, you should be able to simply load using `:- use_module(semweb/rdf11).`   If not, your build/distribution/whatever is incomplete.
